name: Bump Homebrew Formula

on:
  workflow_dispatch:

  push:
    tags:
      - '*'  # Trigger on all tags

jobs:
  update-tap:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Use action to update Homebrew formula
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.ACTIONS_PERSONAL_ACCESS_TOKEN }} # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          user_name: github-actions # Optional, will commit with this user name
          user_email: github-actions@github.com # Optional, will commit with this user email
          message: | # Optional, will commit with this message. Built-in context variables are supported.
            Homebrew formula update for tag [${{ github.ref_name }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}).
            Triggered by @${{ github.actor }} with commit ${{ github.repository }}@${{ github.sha }}.
            For additional details see https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}.
          # org: ORG # Optional, will create tap repo fork in organization
          no_fork: false # Optional, use the origin repository instead of forking
          tap: PeterBrain/homebrew-tap # Optional, defaults to homebrew/core
          formula: icloud-nosync # Formula name, required
          tag: ${{ github.ref }} # Optional, will be determined automatically
          revision: ${{ github.sha }} # Optional, will be determined automatically
          force: false # Optional, if don't want to check for already open PRs
